spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/debt-tracker-db
        driver-class-name: org.postgresql.Driver
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
